import type { Metadata } from "next";
import { encodeSans, lavishlyYours, syne } from "@/lib/fonts";
import "./globals.css";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";
import { motion } from "framer-motion";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light" style={{ colorScheme: 'light' }}>
      <body className={`${encodeSans.variable} ${lavishlyYours.variable} ${syne.variable} antialiased`}>

        <div className="min-h-screen flex flex-col">
          <Header />
          <main className={`${encodeSans.variable} ${lavishlyYours.variable} ${syne.variable} antialiased`}>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
