import type { Metadata } from "next";
import { encodeSans, lavishlyYours } from "@/lib/fonts";
import "./globals.css";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${encodeSans.variable} ${lavishlyYours.variable} antialiased`}>
        <div className="min-h-screen flex flex-col">
          <Header />
          <main className={`${encodeSans.variable} ${lavishlyYours.variable} antialiased`}>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
